server {
    listen 80 default_server;
    server_name 194-87-103-89.sslip.io;
    server_tokens off;
    access_log off;
    location /.well-known/acme-challenge/ { root /var/www/demo-day-acme; }
    location / { return 503; }
}
