const test = require("node:test");
const assert = require("node:assert/strict");
const fs = require("node:fs");
const path = require("node:path");
const os = require("node:os");
const { chromium, expect } = require("@playwright/test");

for (const [name, viewport] of [["desktop", { width: 1440, height: 1000 }], ["mobile", { width: 390, height: 844 }]]) {
  test(`${name}: tabs, organizer login, jury ballot, event archive and new event`, async () => {
    const dir = fs.mkdtempSync(path.join(os.tmpdir(), "voting-ui-"));
    process.env.DATA_FILE = path.join(dir, "db.json");
    process.env.ADMIN_PASSWORD = "ui-admin-password";
    process.env.NODE_ENV = "test";
    fs.writeFileSync(process.env.DATA_FILE, JSON.stringify({
      event: { title: "Demo Day", votingMode: "top3", currentRound: 1 },
      talks: ["Постоянное платежное поручение", "Расширение возможностей управления бизнес-картами в ДБО ЮЛ", "Увеличение доли успешных платежей через редизайн формы"].map((title, i) => ({ id: `fixture-${i}`, title, speaker: "Имя спикера / Payments & Cash Management", description: "Корпораты / Lounge + кухня, 8 этаж / Часть 1", order: i + 1, status: "planned" })),
      voters: [], votes: []
    }));
    delete require.cache[require.resolve("./server")];
    const server = require("./server");
    await new Promise(resolve => server.listen(0, "127.0.0.1", resolve));
    const base = `http://127.0.0.1:${server.address().port}`;
    const browser = await chromium.launch({ headless: true });
    const context = await browser.newContext({ viewport });
    const page = await context.newPage();
    const errors = [];
    page.on("pageerror", error => errors.push(error.message));
    fs.mkdirSync("test-results", { recursive: true });
    const noOverflow = async () => assert.ok(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth + 1), "Page must fit viewport");
    try {
      await page.goto(base + "/admin");
      await page.locator('#loginForm [name="login"]').fill("admin");
      await page.locator('#loginForm [name="password"]').fill("wrong");
      await page.getByRole("button", { name: "Войти", exact: true }).click();
      await expect(page.locator("#loginError")).toHaveText("Неверный логин или пароль");
      await page.locator('#loginForm [name="password"]').fill("ui-admin-password");
      await page.getByRole("button", { name: "Войти", exact: true }).click();
      await expect(page.locator("#dashboard")).toBeVisible();
      await expect(page.locator(".sidebar-title")).toHaveText("Кабинет организатора");
      await expect(page.locator("#talkCount")).toHaveCount(0);
      await expect(page.locator(".event-strip")).not.toBeVisible();
      await expect(page.getByRole("tab", { name: /Результаты|История событий/ })).toHaveCount(0);
      await page.getByRole("tab", { name: "События", exact: true }).click();
      await expect(page.locator(".event-strip")).toBeVisible();
      await expect(page.locator("#newEvent")).toBeDisabled();
      assert.ok(await page.locator(".event-strip").evaluate(el => ["borderLeftWidth", "borderRightWidth", "borderTopWidth", "borderBottomWidth"].every(side => parseFloat(getComputedStyle(el)[side]) > 0)));
      await page.reload();
      await expect(page.locator("#panel-events")).toBeVisible();
      await page.locator("#editEventPresentation").click();
      await page.locator('#presentationForm [name="title"]').fill("Demo Day · Выбор жюри");
      await page.locator('#presentationForm [name="votingIntro"]').fill("Наши лучшие инициативы.\nВыберите свой топ-3 <без HTML>.");
      await page.locator('#presentationForm [type="submit"]').click();
      await expect(page.locator("#presentationDialog")).not.toBeVisible();
      await page.reload();
      await expect(page.locator("#eventTitle")).toHaveText("Demo Day · Выбор жюри");
      await expect(page.locator("#ballotIntroPreview")).toContainText("<без HTML>");
      await noOverflow();
      await page.getByRole("tab", { name: "Выступления", exact: true }).click();
      await expect(page.locator("#activeTalks .active-row")).toHaveCount(3);
      await noOverflow();
      await page.screenshot({ path: `test-results/admin-${name}.png`, fullPage: true });

      await page.getByRole("button", { name: "Добавить выступление", exact: true }).click();
      await page.locator('#talkForm [name="title"]').fill("Проверка & текста <без HTML>");
      await page.locator('#talkForm [type="submit"]').click();
      await expect(page.locator("#activeTalks .active-row")).toHaveCount(4);
      await page.locator('#activeTalks .active-row').last().getByRole("button", { name: "Редактировать", exact: true }).click();
      await expect(page.locator('#talkForm [name="title"]')).toHaveValue("Проверка & текста <без HTML>");
      await page.locator('#talkForm [name="speaker"]').fill("Обновлённая команда");
      await page.locator('#talkForm [name="description"]').fill("Новое описание");
      await page.getByRole("button", { name: "Сохранить изменения", exact: true }).click();
      await expect(page.locator("#talkDialog")).not.toBeVisible();
      await page.reload();
      await expect(page.locator("#activeTalks .active-row").last()).toContainText("Обновлённая команда");
      await expect(page.locator("#activeTalks .active-row").last()).toContainText("Новое описание");
      await expect(page.locator("#activeTalks .active-row")).toHaveCount(4);
      await noOverflow();
      await page.locator('#activeTalks .active-row').last().getByRole("button", { name: "Поднять доклад", exact: true }).click();
      await expect(page.locator("#activeTalks .active-row").nth(2)).toContainText("Проверка & текста <без HTML>");
      await page.locator("#activeTalks .active-row").nth(2).getByRole("button", { name: "Удалить", exact: true }).click();
      await page.locator("#confirmOk").click();
      await expect(page.locator("#activeTalks .active-row")).toHaveCount(3);

      await page.getByRole("tab", { name: /Организаторы/ }).click();
      await expect(page.locator(".event-strip")).not.toBeVisible();
      await page.getByRole("button", { name: "Добавить нового организатора" }).click();
      await page.locator('#organizerForm [name="name"]').fill("Мария Организатор");
      await page.locator('#organizerForm [name="login"]').fill("maria@example.com");
      await page.locator('#organizerForm [name="password"]').fill("maria-password-123");
      await page.locator('#organizerForm [type="submit"]').click();
      await expect(page.locator("#organizers")).toContainText("maria@example.com");
      await noOverflow();
      await page.reload();
      await expect(page.locator("#panel-organizers")).toBeVisible();
      await page.locator(".person-row").filter({ hasText: "maria@example.com" }).getByRole("button", { name: "Сменить пароль" }).click();
      await page.locator('#passwordForm [name="currentPassword"]').fill("wrong");
      await page.locator('#passwordForm [name="password"]').fill("maria-updated-password");
      await page.locator('#passwordForm [name="confirmation"]').fill("does-not-match");
      await page.locator('#passwordForm [type="submit"]').click();
      await expect(page.locator('#passwordForm [data-form-error]')).toHaveText("Новые пароли не совпадают");
      await page.locator('#passwordForm [name="confirmation"]').fill("maria-updated-password");
      await page.locator('#passwordForm [type="submit"]').click();
      await expect(page.locator('#passwordForm [data-form-error]')).toHaveText("Неверный текущий пароль вашего аккаунта");
      await page.locator('#passwordForm [name="currentPassword"]').fill("ui-admin-password");
      await noOverflow();
      await page.screenshot({ path: `test-results/password-${name}.png` });
      await page.locator('#passwordForm [type="submit"]').click();
      await expect(page.locator("#passwordDialog")).not.toBeVisible();
      const colleagueContext = await browser.newContext({ viewport });
      const colleague = await colleagueContext.newPage();
      await colleague.goto(base + "/admin");
      await colleague.locator('#loginForm [name="login"]').fill("maria@example.com");
      await colleague.locator('#loginForm [name="password"]').fill("maria-updated-password");
      await colleague.getByRole("button", { name: "Войти", exact: true }).click();
      await expect(colleague.locator("#currentUser")).toHaveText("Мария Организатор");
      await colleague.locator("#logout").click();
      await expect(colleague.locator("#login")).toBeVisible();
      await colleagueContext.close();

      await page.getByRole("tab", { name: /Жюри/ }).click();
      await expect(page.locator(".event-strip")).not.toBeVisible();
      await page.locator('#voterForm [name="name"]').fill("Иван Жюри");
      await page.locator('#voterForm [type="submit"]').click();
      await expect(page.locator("#voters .voter-row")).toHaveCount(1);
      await noOverflow();
      const juryLink = await page.locator("#voters input").inputValue();
      await page.route("**/api/admin/qr", route => route.fulfill({ status: 503, contentType: "application/json", body: JSON.stringify({ error: "Попробуйте ещё раз" }) }));
      await page.locator(".common-link-row .show-qr").click();
      await expect(page.locator("#qrStatus")).toHaveText("Попробуйте ещё раз");
      await expect(page.locator("#qrDownload")).toBeDisabled();
      await page.unroute("**/api/admin/qr");
      await page.locator("#qrRetry").click();
      await expect(page.locator("#qrImage")).toBeVisible();
      await expect(page.locator("#qrLink")).toHaveValue(base + "/vote");
      await expect(page.locator("#qrLocalWarning")).toBeVisible();
      await page.locator('[data-close="qrDialog"]').click();
      await page.locator("#voters .show-qr").click();
      await expect(page.locator("#qrLink")).toHaveValue(juryLink);
      await expect(page.locator("#qrDescription")).toContainText("Иван Жюри");
      await expect(page.locator("#qrDownload")).toBeEnabled();
      await expect.poll(() => page.locator("#qrImage").evaluate(img => img.complete && img.naturalWidth > 0)).toBe(true);
      await noOverflow();
      assert.ok(await page.locator("#qrDialog").evaluate(el => el.scrollWidth <= el.clientWidth + 1));
      await page.screenshot({ path: `test-results/qr-${name}.png` });
      const downloaded = page.waitForEvent("download");
      await page.locator("#qrDownload").click();
      const download = await downloaded;
      assert.equal(download.suggestedFilename(), "demo-day-jury-qr.png");
      assert.equal(await download.failure(), null);
      const { PNG } = require("pngjs");
      const png = PNG.sync.read(fs.readFileSync(await download.path()));
      assert.equal(require("jsqr")(new Uint8ClampedArray(png.data), png.width, png.height).data, juryLink);
      await page.locator('[data-close="qrDialog"]').click();
      const juryContext = await browser.newContext({ viewport });
      const jury = await juryContext.newPage();
      jury.on("pageerror", error => errors.push(error.message));
      await jury.goto(juryLink);
      await expect(jury.locator(".best-talk")).toHaveCount(3);
      await expect(jury.locator("#ballotTitle")).toHaveText("Demo Day · Выбор жюри");
      await expect(jury.locator("#modeNote")).toHaveText("Наши лучшие инициативы.\nВыберите свой топ-3 <без HTML>.");
      const adminFont = await page.locator("body").evaluate(el => getComputedStyle(el).fontFamily);
      assert.equal(await jury.locator("body").evaluate(el => getComputedStyle(el).fontFamily), adminFont);
      assert.ok(await jury.evaluate(() => document.documentElement.scrollWidth <= innerWidth + 1));
      await jury.screenshot({ path: `test-results/ballot-${name}.png`, fullPage: true });
      await page.getByRole("tab", { name: "Выступления", exact: true }).click();
      await page.locator('[data-mode="top1"]').click();
      await expect(page.locator('[data-mode="top1"]')).toHaveAttribute("aria-pressed", "true");
      await jury.reload();
      await expect(jury.locator("#ballotRound")).toContainText("Топ-1");
      await expect(jury.locator(".points-explainer")).toHaveCount(0);
      await jury.screenshot({ path: `test-results/ballot-top1-${name}.png`, fullPage: true });
      await page.locator('[data-mode="top3"]').click();
      await expect(page.locator('[data-mode="top3"]')).toHaveAttribute("aria-pressed", "true");
      await jury.reload();
      await expect(jury.locator("#ballotRound")).toContainText("Топ-3");
      for (let i = 0; i < 3; i++) await jury.locator(".best-talk").nth(i).click();
      await jury.screenshot({ path: `test-results/ballot-selected-${name}.png`, fullPage: true });
      await jury.locator(".submit-vote").click();
      await expect(jury.getByText("Твой топ-3 сохранен", { exact: true })).toBeVisible();
      await jury.screenshot({ path: `test-results/ballot-result-${name}.png`, fullPage: true });
      await page.getByRole("tab", { name: "События", exact: true }).click();
      await page.locator("#currentStatistics > summary").click();
      await page.locator("#refresh").click();
      await expect(page.locator("#progressBadge")).toHaveText("1 из 1");
      await expect(page.locator("#leaderboard .leader-row")).toHaveCount(3);
      await expect(page.locator("#leaderboard .leader-row").first()).toContainText("2");
      await noOverflow();
      await page.screenshot({ path: `test-results/results-${name}.png`, fullPage: true });

      await page.locator("#completeEvent").click();
      await page.locator("#confirmOk").click();
      await expect(page.locator("#eventStatus")).toHaveText("Событие завершено");
      await expect(page.locator("#editEventPresentation")).toBeDisabled();
      await page.getByRole("tab", { name: /Выступления/ }).click();
      await expect(page.locator(".edit-talk").first()).toBeDisabled();
      await jury.reload();
      await expect(jury.getByRole("heading", { name: "Голосование завершено" })).toBeVisible();
      await expect(jury.locator(".edit-vote")).toHaveCount(0);
      await page.getByRole("tab", { name: "События", exact: true }).click();
      await page.getByRole("button", { name: "Посмотреть результаты" }).click();
      await expect(page.locator("#historyDetail")).toContainText("Иван Жюри");
      await page.locator('[data-history-round="2"]').click();
      await expect(page.locator("#historyDetail")).toContainText("Голосов: 0");
      await noOverflow();
      await page.screenshot({ path: `test-results/events-archive-${name}.png`, fullPage: true });
      await expect(page.locator("#newEvent")).toBeEnabled();
      await page.locator("#newEvent").click();
      await page.locator('#eventForm [name="title"]').fill("Следующий Demo Day");
      await page.locator('#eventForm [type="submit"]').click();
      await expect(page.locator("#eventTitle")).toHaveText("Следующий Demo Day");
      await expect(page.locator("#activeTalks .active-row")).toHaveCount(0);
      await page.getByRole("tab", { name: "События", exact: true }).click();
      await expect(page.locator("#historyList .history-row")).toHaveCount(1);
      await expect(page.locator("#historyDetail")).not.toBeVisible();
      await page.getByRole("button", { name: "Посмотреть результаты" }).click();
      await expect(page.locator("#historyDetail")).toContainText("Иван Жюри");
      await page.goto(base + "/admin#results");
      await expect(page.locator("#panel-events")).toBeVisible();
      await expect(page.locator("#metrics")).toBeVisible();
      await page.goto(base + "/admin#history");
      await expect(page.locator("#historyList .history-row")).toBeVisible();
      await jury.reload();
      await expect(jury.getByRole("heading", { name: "Это приглашение больше не действует" })).toBeVisible();
      await jury.goto(base + "/?public=1");
      await expect(jury.getByRole("heading", { name: "Программа готовится" })).toBeVisible();
      await juryContext.close();
      await page.getByRole("tab", { name: /Организаторы/ }).click();
      await page.locator(".person-row").filter({ hasText: "Это вы" }).getByRole("button", { name: "Сменить пароль" }).click();
      await page.locator('#passwordForm [name="currentPassword"]').fill("ui-admin-password");
      await page.locator('#passwordForm [name="password"]').fill("ui-updated-password");
      await page.locator('#passwordForm [name="confirmation"]').fill("ui-updated-password");
      await page.locator('#passwordForm [type="submit"]').click();
      await expect(page.locator("#passwordDialog")).not.toBeVisible();
      await page.reload();
      await expect(page.locator("#panel-organizers")).toBeVisible();
      assert.deepEqual(errors, []);
    } finally {
      await browser.close();
      await new Promise(resolve => server.close(resolve));
    }
  });
}
